version: "3"
services:

  otel-collector:
    container_name: otel-collector-validadorjwt
    image: otel/opentelemetry-collector-contrib:0.95.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector-config.yaml
    volumes:
      - ./cfg/otel-collector-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin
  
  prometheus:
    container_name: prometheus-validatorjwt
    image: prom/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    container_name: loki-validatorjwt
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  tempo:
    container_name: tempo-validatorjwt
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./cfg/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
  
  grafana:
    container_name: grafana-validadorjwt
    image: grafana/grafana
    restart: always
    volumes:
      - ./cfg/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./cfg/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"

  zipkin:
    container_name: zipkin-validadorjwt
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
