spring:
  application:
    name: validadorjwt
constraints:
  jwt:
    tamanhomaximo: 1000
  name:
    tamanhomaximo: 256
  seed:
    valormaximo: 2147483647
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health
  metrics:
    tags:
      application: validadorjwt
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
otlp:
  endpoint: http://localhost:4317